# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name=b'View Count'),
        ),
    ]
